version: "latest"

services:
  frontend:
    build: ./client
    ports:
      - "5173:80"
  backend:
    build: ./server
    ports:
      - "3000:5000"
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5433
  postgres:
    build: ./db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
     POSTGRES_HOST: localhost 
     POSTGRES_PORT: 5433
     POSTGRES_USERNAME: postgres
     POSTGRES_PASSWORD: 12345678
     POSTGRES_DATABASE: store
volumes:
  postgres_data: {}
