services:
  postgres:
    image: "postgres:latest"
    environment:
       POSTGRES_HOST: postgres
       POSTGRES_PORT: 5432
       POSTGRES_USER: postgres
       POSTGRES_PASSWORD: 123456789
       POSTGRES_DB: store
       JWT_KEY: 123456
    networks:
      - app-network
  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "3050:80"
    networks:
      - app-network
  api:
    build:
      dockerfile: Dockerfile
      context: "./server"
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=store
      - POSTGRES_PASSWORD=123456789
      - POSTGRES_PORT=5432
    ports:
      - "3000:3000"
    networks:
      - app-network
  client:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile
      context: ./client
    ports:
      - "5173:5173"  
    volumes:
      - /app/node_modules
      - ./client:/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

